#!/usr/bin/env python3
"""Generate gf180/sim/gf180_sdm3_mb.spice: 4-bit (15-level flash) variant of
gf180_sdm3.spice for fs=512 kHz.

- sdm3 loop timing/coefficients unchanged (a1=d1=2, a2=0.5, d2=1;
  NTF=(1-z^-1)^2). int1 uses the phase-1 winning CI1x2 sizing
  (CS1=16p, CI1=8p; 15 DAC units x 1p per side = 12.5 mV/unit-step = 0.25
  model units = d1*dy exactly). int2: CS2=2p, CI2=4p, 15 DAC units x 0.25p.
- Flash: 15x gf180_strongarm + NAND SR latch (same cells as 1-bit; hysteresis
  proven benign). Thresholds via ideal series offset sources THSTEP=6.25 mV
  differential per step (covers measured behavioral x2 range +/-40 mV);
  these stand in for a resistive ladder (documented - needs real ladder in
  layout/RTL phase).
- DWA: behavioral (B-sources + cap registers + idsw switches): single
  rotating pointer p over 15 units; P-side "up" count = 15-c, N-side
  complementary; p[n+1] = (p[n] - c[n]) mod 15. int2 DAC: straight
  thermometer from the PH2-registered code C2 (its mismatch is shaped by
  int1; DWA not applied - documented scope decision).
  ALL of this logic must be re-implemented in RTL for silicon.
"""
import sys

NU = 15          # units per side
THSTEP = 6.25e-3 # V per threshold step (differential)

L = []
A = L.append
A("* gf180_sdm3_mb.spice - 4-bit (15-level) sdm3 variant for fs=512 kHz")
A("* GENERATED by gen_sdm3_mb.py - do not edit by hand.")
A("* All behavioral B-sources are RC-smoothed current-source form")
A("* (target-v)/R into a hold cap, and all floor()/ternary logic is")
A("* replaced by steep sigmoids: ngspice-46 fails to converge on")
A("* discontinuous B-source branches (timestep-too-small at the input")
A("* zero crossing, t=62.5026 ms). Sigmoid offsets put the transition")
A("* between settled integer states, so settled values are exact.")
A("* Requires: gf180_afe_cells.spice (OTA/TG/bias) + gf180_sdm3.spice")
A("* (strongarm, nand2, inv). Loop timing/coefficients identical to sdm3.")
A("* Flash thresholds and DWA/thermometer logic are BEHAVIORAL (ideal")
A("* sources / B-sources) - silicon needs a ladder + DWA RTL.")
A("")
A("* ---- 15-level flash: strongarm + SR latch per slice ----")
A("* H_i=1 <=> O2D > theta_i, theta_i=(i-7)*6.25mV; H_i is the latch's NBIT")
A("* terminal (BIT_i=1 <=> O2D<theta_i, same convention as 1-bit sdm3).")
A(".subckt gf180_sdm3_flash15 O2P O2N CMPCK VDD33 VSS " +
  " ".join(f"H{i}" for i in range(NU)))
for i in range(NU):
    off = (i - 7) * THSTEP / 2
    A(f"* slice {i}: theta={2*off*1e3:+.2f} mV diff")
    A(f"VOFFP{i} O2P INPP{i} {-off:.6e}")
    A(f"VOFFN{i} O2N INNN{i} {+off:.6e}")
    A(f"XCMP{i} INPP{i} INNN{i} QP{i} QN{i} CMPCK VDD33 VSS gf180_strongarm")
    A(f"CQP{i} QP{i} VSS 0.5p")
    A(f"CQN{i} QN{i} VSS 0.5p")
    A(f"XND1{i} QP{i} H{i} BIT{i} VDD33 VSS gf180_sdm3_nand2")
    A(f"XND2{i} QN{i} BIT{i} H{i} VDD33 VSS gf180_sdm3_nand2")
A(".ends gf180_sdm3_flash15")
A("")

# ---- int1 multibit: sampled input (CS=16p) + 15-unit DAC (1p units), CI=8p
A("* ---- int1 mb: CS=16p sampled input + 15x1p/side direct DAC, CI=8p ----")
A("* SELP_j/SELN_j: 0/VDD level, unit j P-side left plate -> VP if SELP_j,")
A("* else VN during PH2 (complement on N side: SELN_j=1 -> NP side to VP).")
A(".subckt gf180_sdm3_int1_mb INP_S INN_S VCM_REF VP VN OUTP OUTN PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"SP{j}" for j in range(NU)) + " " + " ".join(f"SN{j}" for j in range(NU)) +
  " params: CS=16p CU=1p CI=8p W91=11u L91=2u W92=6u L92=2u W10=12u RSET=25k CC=10p")
A("XOTA INP INN VCM_REF OUTP OUTN VDD33 VSS gf180_fd_ota_full2_nc W91={W91} L91={L91} W92={W92} L92={L92} W10={W10} RSET={RSET} CC={CC}")
A("CSP CSLP CSRP {CS}")
A("CSN CSLN CSRN {CS}")
A("XS1A CSLP INP_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1B CSRP VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1C CSLN INN_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1D CSRN VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS2A CSLP VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2B CSRP INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2C CSLN VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2D CSRN INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
for j in range(NU):
    A(f"* DAC unit {j} (P side DP{j}, N side DN{j})")
    A(f"CDP{j} CDLP{j} CDRP{j} {{CU}}")
    A(f"CDN{j} CDLN{j} CDRN{j} {{CU}}")
    A(f"XDPA{j} CDLP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDPB{j} CDRP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNA{j} CDLN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNB{j} CDRN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDP2{j} CDRP{j} INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    A(f"XDN2{j} CDRN{j} INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    # gate drives: PH2 AND SEL, RC-smoothed current-source form (tau ~2 ns)
    A(f"BGPP{j} GPP{j} VSS I=(v(GPP{j})-v(PH2)*v(SP{j})/v(VDD33))/1k")
    A(f"BGPN{j} GPN{j} VSS I=(v(GPN{j})-v(PH2)*(v(VDD33)-v(SP{j}))/v(VDD33))/1k")
    A(f"BGNP{j} GNP{j} VSS I=(v(GNP{j})-v(PH2)*v(SN{j})/v(VDD33))/1k")
    A(f"BGNN{j} GNN{j} VSS I=(v(GNN{j})-v(PH2)*(v(VDD33)-v(SN{j}))/v(VDD33))/1k")
    A(f"BNOPP{j} NGPP{j} 0 V=v(VDD33)-v(GPP{j})")
    A(f"BNOPN{j} NGPN{j} 0 V=v(VDD33)-v(GPN{j})")
    A(f"BNONP{j} NGNP{j} 0 V=v(VDD33)-v(GNP{j})")
    A(f"BNONN{j} NGNN{j} 0 V=v(VDD33)-v(GNN{j})")
    A(f"CGPP{j} GPP{j} VSS 2p")
    A(f"CGPN{j} GPN{j} VSS 2p")
    A(f"CGNP{j} GNP{j} VSS 2p")
    A(f"CGNN{j} GNN{j} VSS 2p")
    A(f"CNGPP{j} NGPP{j} VSS 0.2p")
    A(f"CNGPN{j} NGPN{j} VSS 0.2p")
    A(f"CNGNP{j} NGNP{j} VSS 0.2p")
    A(f"CNGNN{j} NGNN{j} VSS 0.2p")
    A(f"XPVP{j} CDLP{j} VP GPP{j} NGPP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XPVN{j} CDLP{j} VN GPN{j} NGPN{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVP{j} CDLN{j} VP GNP{j} NGNP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVN{j} CDLN{j} VN GNN{j} NGNN{j} VDD33 VSS gf180_tg_lowq")
A("CIP OUTN INP {CI}")
A("CIN OUTP INN {CI}")
A("RBIASP INP VCM_REF 10G")
A("RBIASN INN VCM_REF 10G")
A(".ends gf180_sdm3_int1_mb")
A("")

# ---- int2 multibit: parasitic-insensitive, CS=2p CI=4p, 15x0.25p DAC ----
A("* ---- int2 mb: CS=2p, CI=4p, 15x0.25p/side DAC (S2P/S2N selects, PH1 int)")
A("* int2 integrates during PH1 with the REGISTERED code (applied via S2*).")
A(".subckt gf180_sdm3_int2_mb INP_S INN_S VCM_REF VP VN OUTP OUTN PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"S2P{j}" for j in range(NU)) + " " + " ".join(f"S2N{j}" for j in range(NU)) +
  " params: CS=2p CU=0.25p CI=4p W91=11u L91=2u W92=6u L92=2u W10=12u RSET=25k CC=10p")
A("XOTA INP INN VCM_REF OUTP OUTN VDD33 VSS gf180_fd_ota_full2_nc W91={W91} L91={L91} W92={W92} L92={L92} W10={W10} RSET={RSET} CC={CC}")
A("CSP CSLP CSRP {CS}")
A("CSN CSLN CSRN {CS}")
# int2 (gf180_sd_int) is clocked with swapped phases by the parent; inside,
# PH1 = its sampling phase, PH2 = integration. Mirror gf180_sd_int structure:
# sample: XS1* on PH1 (input), XS2* on PH2 (transfer); DAC plates to VCM on
# PH2 (its idle) and to VP/VN during PH1 (its integration) via S2 selects.
A("XS1A CSLP INP_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1B CSRP VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1C CSLN INN_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1D CSRN VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS2A CSLP VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2B CSRP INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2C CSLN VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2D CSRN INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
for j in range(NU):
    A(f"* DAC unit {j}")
    A(f"CDP{j} CDLP{j} CDRP{j} {{CU}}")
    A(f"CDN{j} CDLN{j} CDRN{j} {{CU}}")
    # right plates: VCM during internal PH1 (sampling), INP/INN during
    # internal PH2 (integration) - same as 1-bit gf180_sd_int
    A(f"XDP1{j} CDRP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDP2{j} CDRP{j} INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    A(f"XDN1{j} CDRN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDN2{j} CDRN{j} INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    # left plates: VCM during internal PH1, VP/VN per S2 select during
    # internal PH2 (integration)
    A(f"BGPP{j} GPP{j} VSS I=(v(GPP{j})-v(PH2)*v(S2P{j})/v(VDD33))/1k")
    A(f"BGPN{j} GPN{j} VSS I=(v(GPN{j})-v(PH2)*(v(VDD33)-v(S2P{j}))/v(VDD33))/1k")
    A(f"BGNP{j} GNP{j} VSS I=(v(GNP{j})-v(PH2)*v(S2N{j})/v(VDD33))/1k")
    A(f"BGNN{j} GNN{j} VSS I=(v(GNN{j})-v(PH2)*(v(VDD33)-v(S2N{j}))/v(VDD33))/1k")
    A(f"BNOPP{j} NGPP{j} 0 V=v(VDD33)-v(GPP{j})")
    A(f"BNOPN{j} NGPN{j} 0 V=v(VDD33)-v(GPN{j})")
    A(f"BNONP{j} NGNP{j} 0 V=v(VDD33)-v(GNP{j})")
    A(f"BNONN{j} NGNN{j} 0 V=v(VDD33)-v(GNN{j})")
    A(f"CGPP{j} GPP{j} VSS 2p")
    A(f"CGPN{j} GPN{j} VSS 2p")
    A(f"CGNP{j} GNP{j} VSS 2p")
    A(f"CGNN{j} GNN{j} VSS 2p")
    A(f"CNGPP{j} NGPP{j} VSS 0.2p")
    A(f"CNGPN{j} NGPN{j} VSS 0.2p")
    A(f"CNGNP{j} NGNP{j} VSS 0.2p")
    A(f"CNGNN{j} NGNN{j} VSS 0.2p")
    A(f"XPVP{j} CDLP{j} VP GPP{j} NGPP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XPVN{j} CDLP{j} VN GPN{j} NGPN{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVP{j} CDLN{j} VP GNP{j} NGNP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVN{j} CDLN{j} VN GNN{j} NGNN{j} VDD33 VSS gf180_tg_lowq")
    # internal PH1 (sampling): left plates to VCM (discharge)
    A(f"XDPC{j} CDLP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNC{j} CDLN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("CIP OUTN INP {CI}")
A("CIN OUTP INN {CI}")
A("RBIASP INP VCM_REF 10G")
A("RBIASN INN VCM_REF 10G")
A(".ends gf180_sdm3_int2_mb")
A("")

# ---- top-level modulator with behavioral DWA / thermometer logic ----
A("* ---- modulator top: sdm3 timing, 4-bit flash + behavioral DWA ----")
A("* Nodes: TH0..TH14 = thermometer lines (H_i). External PUP clock (narrow")
A("* pulse at PH1 rising edge) advances the DWA master register.")
A(".subckt gf180_sdm3_mod_mb VINP VINN VCM_REF VP VN PH1 NPH1 PH2 NPH2 CMPCK PUP VDD33 VSS " +
  " ".join(f"TH{i}" for i in range(NU)) +
  " params: RSET=25k CC=10p")
A("XINT1 VINN VINP VCM_REF VP VN O1P O1N PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"SEL{j}" for j in range(NU)) + " " + " ".join(f"SELN{j}" for j in range(NU)) +
  " gf180_sdm3_int1_mb RSET={RSET} CC={CC}")
A("* int2 with swapped clock pins (samples PH2 / integrates PH1)")
A("XINT2 O1N O1P VCM_REF VP VN O2P O2N PH2 NPH2 PH1 NPH1 VDD33 VSS " +
  " ".join(f"SEL2{j}" for j in range(NU)) + " " + " ".join(f"SEL2N{j}" for j in range(NU)) +
  " gf180_sdm3_int2_mb RSET={RSET} CC={CC}")
A("XFLASH O2P O2N CMPCK VDD33 VSS " +
  " ".join(f"TH{i}" for i in range(NU)) + " gf180_sdm3_flash15")
A("* thermometer count as voltage (1 V per count), RC-filtered (tau ~4 ns)")
for i in range(NU):
    A(f"RTHF{i} TH{i} THF{i} 2k")
    A(f"CTHF{i} THF{i} VSS 2p")
A("BCSUM CSUM 0 V=(" + "+".join(f"v(THF{i})" for i in range(NU)) + ")/v(VDD33)")
A("* DWA pointer: master samples mod(p_slave - c + 15) during PUP,")
A("* slave tracks master during PH2. p[n+1]=(p[n]-c[n]) mod 15.")
A("* wrap via steep sigmoid of PNEXT (exact at settled integer states)")
A("BNEXT PNEXT 0 V=v(PTRS)-v(CSUM)+15")
A("BNEXTM PNEXTM 0 V=v(PNEXT)-15/(1+exp((14.5-v(PNEXT))/0.05))")
A("* B-source current sample/hold with sigmoid clock gating")
A("(idsw SW broke transient OP; discontinuous gating breaks tran conv)")
A("BSHM PTRM VSS I=(v(PTRM)-v(PNEXTM))/1k/(1+exp((2.2-v(PUP))/0.05))")
A("CPTRM PTRM VSS 10p")
A("RPTRM PTRM VSS 1T")
A("BSHS PTRS VSS I=(v(PTRS)-v(PTRM))/1k/(1+exp((2.2-v(PH2))/0.05))")
A("CPTRS PTRS VSS 10p")
A("RPTRS PTRS VSS 1T")
A(".nodeset V(PTRS)=0 V(PTRM)=0" if False else "*")
A("* int1 unit selects (DWA): P-side unit j -> VP if rot(j-p) < 15-c.")
A("* rot via sigmoid wrap of (j-p); sigmoid select; RC-smoothed (tau ~2 ns)")
for j in range(NU):
    A(f"BSEL{j} SEL{j} VSS I=(v(SEL{j})-v(VDD33)/(1+exp((({j}-v(PTRS))+15/(1+exp(({j}-v(PTRS)+0.5)/0.05))+0.5-(15-v(CSUM)))/0.15)))/1k")
    A(f"BSELN{j} SELN{j} VSS I=(v(SELN{j})-(v(VDD33)-v(SEL{j})))/1k")
A("* int2 code register: tracks CSUM during PH2, holds through PH1")
A("* (smoothed B-source sample/hold; idsw SW broke transient OP)")
A("BC2R C2R VSS I=(v(C2R)-v(CSUM))/1k/(1+exp((2.0-v(PH2))/0.05))")
A("CC2R C2R VSS 0.5p")
A("RC2R C2R VSS 1G")
A("* int2 unit selects (straight thermometer from registered code)")
for j in range(NU):
    A(f"BSEL2{j} SEL2{j} VSS I=(v(SEL2{j})-v(VDD33)/(1+exp(({j}+0.5-(15-v(C2R)))/0.15)))/1k")
    A(f"BSEL2N{j} SEL2N{j} VSS I=(v(SEL2N{j})-(v(VDD33)-v(SEL2{j})))/1k")
for j in range(NU):
    A(f"CSEL{j} SEL{j} VSS 2p")
    A(f"CSELN{j} SELN{j} VSS 2p")
    A(f"CSEL2{j} SEL2{j} VSS 2p")
    A(f"CSEL2N{j} SEL2N{j} VSS 2p")
A("CCSUM CSUM VSS 0.5p")
A("CPNEXT PNEXT VSS 0.2p")
A("CPNEXTM PNEXTM VSS 0.2p")
A(".ends gf180_sdm3_mod_mb")

open("gf180_sdm3_mb.spice", "w").write("\n".join(L) + "\n")
print(f"wrote gf180_sdm3_mb.spice: {len(L)} lines")
