#!/usr/bin/env python3
"""Generate gf180/sim/gf180_sdm3_mb_tl.spice: 4-bit sdm3 variant with
ALL-TRANSISTOR thermometer select logic (no behavioral B-sources in any
select/gate path). Motivation: ngspice-46 dies deterministically with
"timestep too small" on B-source branch discontinuities (62.502 ms artifact,
5 reproductions across netlist variants).

Key identity (straight thermometer, bubble-free by construction):
  P-side DAC unit j goes to VP  <=>  j < 15 - c  <=>  NOT H_{14-j}
  where H_i = flash latch output (1 <=> O2D > theta_i), c = thermometer code.
So the thermometer->DAC mapping is a WIRE PERMUTATION plus PH2-gating via
gf180_sdm3_nand2/inv. int2's DAC uses the same mapping on H2_i = the
PH2-registered H_i (gf180_sdm3_dff, mirrors the 1-bit BIT2 re-timing).

Same integrator cells / flash as gf180_sdm3_mb.spice. Loop timing and
coefficients identical to sdm3 (NTF=(1-z^-1)^2, a1=d1=2, a2=0.5, d2=1).
"""
NU = 15
THSTEP = 6.25e-3

L = []
A = L.append
A("* gf180_sdm3_mb_tl.spice - 4-bit sdm3, ALL-TRANSISTOR select logic")
A("* GENERATED by gen_sdm3_mb_tl.py - do not edit by hand.")
A("* No behavioral B-sources anywhere (ngspice 62.502 ms artifact avoidance).")
A("* Requires gf180_afe_cells.spice + gf180_sdm3.spice (cells).")
A("")

# ---------------- flash (identical to gf180_sdm3_mb) ----------------
A(".subckt gf180_sdm3_flash15 O2P O2N CMPCK VDD33 VSS " +
  " ".join(f"H{i}" for i in range(NU)))
for i in range(NU):
    off = (i - 7) * THSTEP / 2
    A(f"* slice {i}: theta={2*off*1e3:+.2f} mV diff")
    A(f"VOFFP{i} O2P INPP{i} {-off:.6e}")
    A(f"VOFFN{i} O2N INNN{i} {+off:.6e}")
    A(f"XCMP{i} INPP{i} INNN{i} QP{i} QN{i} CMPCK VDD33 VSS gf180_strongarm")
    A(f"CQP{i} QP{i} VSS 0.5p")
    A(f"CQN{i} QN{i} VSS 0.5p")
    A(f"XND1{i} QP{i} H{i} BIT{i} VDD33 VSS gf180_sdm3_nand2")
    A(f"XND2{i} QN{i} BIT{i} H{i} VDD33 VSS gf180_sdm3_nand2")
A(".ends gf180_sdm3_flash15")
A("")

# ---------------- int1_mb ----------------
A(".subckt gf180_sdm3_int1_mb INP_S INN_S VCM_REF VP VN OUTP OUTN PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"SP{j}" for j in range(NU)) + " " + " ".join(f"SN{j}" for j in range(NU)) +
  " params: CS=16p CU=1p CI=8p W91=11u L91=2u W92=6u L92=2u W10=12u RSET=25k CC=10p")
A("XOTA INP INN VCM_REF OUTP OUTN VDD33 VSS gf180_fd_ota_full2_nc W91={W91} L91={L91} W92={W92} L92={L92} W10={W10} RSET={RSET} CC={CC}")
A("CSP CSLP CSRP {CS}")
A("CSN CSLN CSRN {CS}")
A("XS1A CSLP INP_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1B CSRP VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1C CSLN INN_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1D CSRN VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS2A CSLP VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2B CSRP INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2C CSLN VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2D CSRN INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
for j in range(NU):
    A(f"* DAC unit {j} (P side DP{j}, N side DN{j}); SP/SN are logic levels")
    A(f"CDP{j} CDLP{j} CDRP{j} {{CU}}")
    A(f"CDN{j} CDLN{j} CDRN{j} {{CU}}")
    A(f"XDPA{j} CDLP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDPB{j} CDRP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNA{j} CDLN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNB{j} CDRN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDP2{j} CDRP{j} INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    A(f"XDN2{j} CDRN{j} INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    # gates: NGPP = ~(PH2 & SP), GPP = PH2 & SP ; same for SN path
    A(f"XNDGPP{j} PH2 SP{j} NGPP{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGPP{j} NGPP{j} GPP{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNDGPN{j} PH2 SN{j} NGPN{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGPN{j} NGPN{j} GPN{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XPVP{j} CDLP{j} VP GPP{j} NGPP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XPVN{j} CDLP{j} VN GPN{j} NGPN{j} VDD33 VSS gf180_tg_lowq")
    # N side mirror: unit DN{j} uses SN{j} for VP, SP{j} for VN
    A(f"XNDGNP{j} PH2 SN{j} NGNP{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGNP{j} NGNP{j} GNP{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNDGNN{j} PH2 SP{j} NGNN{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGNN{j} NGNN{j} GNN{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNVP{j} CDLN{j} VP GNP{j} NGNP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVN{j} CDLN{j} VN GNN{j} NGNN{j} VDD33 VSS gf180_tg_lowq")
A("CIP OUTN INP {CI}")
A("CIN OUTP INN {CI}")
A("RBIASP INP VCM_REF 10G")
A("RBIASN INN VCM_REF 10G")
A(".ends gf180_sdm3_int1_mb")
A("")

# ---------------- int2_mb ----------------
A(".subckt gf180_sdm3_int2_mb INP_S INN_S VCM_REF VP VN OUTP OUTN PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"S2P{j}" for j in range(NU)) + " " + " ".join(f"S2N{j}" for j in range(NU)) +
  " params: CS=2p CU=0.25p CI=4p W91=11u L91=2u W92=6u L92=2u W10=12u RSET=25k CC=10p")
A("XOTA INP INN VCM_REF OUTP OUTN VDD33 VSS gf180_fd_ota_full2_nc W91={W91} L91={L91} W92={W92} L92={L92} W10={W10} RSET={RSET} CC={CC}")
A("CSP CSLP CSRP {CS}")
A("CSN CSLN CSRN {CS}")
A("XS1A CSLP INP_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1B CSRP VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1C CSLN INN_S PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS1D CSRN VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
A("XS2A CSLP VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2B CSRP INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2C CSLN VCM_REF PH2 NPH2 VDD33 VSS gf180_tg_lowq")
A("XS2D CSRN INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
for j in range(NU):
    A(f"* DAC unit {j}")
    A(f"CDP{j} CDLP{j} CDRP{j} {{CU}}")
    A(f"CDN{j} CDLN{j} CDRN{j} {{CU}}")
    # right plates: VCM during internal PH1 (sampling), INP/INN during PH2
    A(f"XDP1{j} CDRP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDP2{j} CDRP{j} INP PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    A(f"XDN1{j} CDRN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDN2{j} CDRN{j} INN PH2 NPH2 VDD33 VSS gf180_tg_lowq")
    # left plates: VCM during internal PH1, VP/VN per S2 during internal PH2
    A(f"XDPC{j} CDLP{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XDNC{j} CDLN{j} VCM_REF PH1 NPH1 VDD33 VSS gf180_tg_lowq")
    A(f"XNDGPP{j} PH2 S2P{j} NGPP{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGPP{j} NGPP{j} GPP{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNDGPN{j} PH2 S2N{j} NGPN{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGPN{j} NGPN{j} GPN{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XPVP{j} CDLP{j} VP GPP{j} NGPP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XPVN{j} CDLP{j} VN GPN{j} NGPN{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNDGNP{j} PH2 S2N{j} NGNP{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGNP{j} NGNP{j} GNP{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNDGNN{j} PH2 S2P{j} NGNN{j} VDD33 VSS gf180_sdm3_nand2")
    A(f"XIGNN{j} NGNN{j} GNN{j} VDD33 VSS gf180_sdm3_inv")
    A(f"XNVP{j} CDLN{j} VP GNP{j} NGNP{j} VDD33 VSS gf180_tg_lowq")
    A(f"XNVN{j} CDLN{j} VN GNN{j} NGNN{j} VDD33 VSS gf180_tg_lowq")
A("CIP OUTN INP {CI}")
A("CIN OUTP INN {CI}")
A("RBIASP INP VCM_REF 10G")
A("RBIASN INN VCM_REF 10G")
A(".ends gf180_sdm3_int2_mb")
A("")

# ---------------- top modulator ----------------
A(".subckt gf180_sdm3_mod_mb VINP VINN VCM_REF VP VN PH1 NPH1 PH2 NPH2 CMPCK PUP VDD33 VSS " +
  " ".join(f"TH{i}" for i in range(NU)) +
  " params: RSET=25k CC=10p")
# int1 selects: SP{j}=THN{14-j}, SN{j}=TH{14-j}  (wire permutation)
A("XINT1 VINN VINP VCM_REF VP VN O1P O1N PH1 NPH1 PH2 NPH2 VDD33 VSS " +
  " ".join(f"THN{14-j}" for j in range(NU)) + " " +
  " ".join(f"TH{14-j}" for j in range(NU)) +
  " gf180_sdm3_int1_mb RSET={RSET} CC={CC}")
# int2 selects from registered H2: S2P{j}=H2N{14-j}, S2N{j}=H2{14-j}
A("XINT2 O1N O1P VCM_REF VP VN O2P O2N PH2 NPH2 PH1 NPH1 VDD33 VSS " +
  " ".join(f"H2N{14-j}" for j in range(NU)) + " " +
  " ".join(f"H2{14-j}" for j in range(NU)) +
  " gf180_sdm3_int2_mb RSET={RSET} CC={CC}")
A("XFLASH O2P O2N CMPCK VDD33 VSS " +
  " ".join(f"TH{i}" for i in range(NU)) + " gf180_sdm3_flash15")
# inverters for the select wiring
for i in range(NU):
    A(f"XITHN{i} TH{i} THN{i} VDD33 VSS gf180_sdm3_inv")
# PH2-edge code register (mirrors 1-bit BIT2 DFF)
for i in range(NU):
    A(f"XH2D{i} TH{i} H2{i} PH2 NPH2 VDD33 VSS gf180_sdm3_dff")
for i in range(NU):
    A(f"XIH2N{i} H2{i} H2N{i} VDD33 VSS gf180_sdm3_inv")
A(".ends gf180_sdm3_mod_mb")

open("gf180_sdm3_mb_tl.spice", "w").write("\n".join(L) + "\n")
print(f"wrote gf180_sdm3_mb_tl.spice: {len(L)} lines")
